<?php
return [
    "projects" => [
        [
            'repo_name' => 'html-css-toboolist',
            'repo_link' => 'https://github.com/Dan848/html-css-toboolist',
            'name' => 'To BooList Layout',
            'description' => 'Descrizione',
            'image' => '/img/projects/to-boo-list.jpg',
            'created_on' => '2023-01-31',
            'fe_be_oriented' => true,
            'technology_id' => 1,
        ],
        [
            'repo_name' => 'htmlcss-discord',
            'repo_link' => 'https://github.com/Dan848/htmlcss-discord',
            'name' => 'Discord Layout',
            'description' => 'Descrizione',
            'image' => '/img/projects/discord.jpg',
            'created_on' => '2023-02-07',
            'fe_be_oriented' => true,
            'technology_id' => 1,
        ],
        [
            'repo_name' => 'htmlcss-dropbox',
            'repo_link' => 'https://github.com/Dan848/htmlcss-dropbox',
            'name' => 'Dropbox Layout',
            'description' => 'Descrizione',
            'image' => '/img/projects/dropbox.jpg',
            'created_on' => '2023-02-13',
            'fe_be_oriented' => true,
            'technology_id' => 1,
        ],
        [
            'repo_name' => 'html-css-spotifyweb',
            'repo_link' => 'https://github.com/Dan848/html-css-spotifyweb',
            'name' => 'Spotifyweb Layout',
            'description' => 'Descrizione',
            'image' => '/img/projects/spotify.jpg',
            'created_on' => '2023-02-22',
            'fe_be_oriented' => true,
            'technology_id' => 1,
        ],
        [
            'repo_name' => 'html-css-bootstrap-dashboard',
            'repo_link' => 'https://github.com/Dan848/html-css-bootstrap-dashboard',
            'name' => 'Bootstrap Dashboard Layout',
            'description' => 'Descrizione',
            'image' => '/img/projects/bootstrap-dashboard.jpg',
            'created_on' => '2023-03-01',
            'fe_be_oriented' => true,
            'technology_id' => 3,
        ],
        [
            'repo_name' => 'js-campominato-dom',
            'repo_link' => 'https://github.com/Dan848/js-campominato-dom',
            'name' => 'Campo Minato Javascript',
            'description' => 'Descrizione',
            'image' => '/img/projects/campo-minato.jpg',
            'created_on' => '2023-03-21',
            'fe_be_oriented' => true,
            'technology_id' => 2,
        ],
        [
            'repo_name' => 'vue-todolist',
            'repo_link' => 'https://github.com/Dan848/vue-todolist',
            'name' => 'To Duck List Vue',
            'description' => 'Descrizione',
            'image' => '/img/projects/to-duck-list.jpg',
            'created_on' => '2023-03-30',
            'fe_be_oriented' => true,
            'technology_id' => 5,
        ],
        [
            'repo_name' => 'vue-boolzapp',
            'repo_link' => 'https://github.com/Dan848/vue-boolzapp',
            'name' => 'Boolzapp Vue',
            'description' => 'Descrizione',
            'image' => '/img/projects/boolzapp.jpg',
            'created_on' => '2023-04-11',
            'fe_be_oriented' => true,
            'technology_id' => 5,
        ],
        [
            'repo_name' => 'vite-boolflix',
            'repo_link' => 'https://github.com/Dan848/vite-boolflix',
            'name' => 'Boolflix Vite',
            'description' => 'Descrizione',
            'image' => '/img/projects/boolflix.jpg',
            'created_on' => '2023-04-26',
            'fe_be_oriented' => true,
            'technology_id' => 6,
        ],
        [
            'repo_name' => 'proj-html-vuejs',
            'repo_link' => 'https://github.com/Dan848/proj-html-vuejs',
            'name' => 'Anidio Page',
            'description' => 'Descrizione',
            'image' => '/img/projects/anidio.jpg',
            'created_on' => '2023-04-28',
            'fe_be_oriented' => true,
            'technology_id' => 6,
        ],
        [
            'repo_name' => 'php-badwords',
            'repo_link' => 'https://github.com/Dan848/php-badwords',
            'name' => 'Badwords Php',
            'description' => 'Descrizione',
            'image' => '/img/projects/badwords.jpg',
            'created_on' => '2023-04-28',
            'fe_be_oriented' => false,
            'technology_id' => 7,
        ],
        [
            'repo_name' => 'php-todo-list-json',
            'repo_link' => 'https://github.com/Dan848/php-todo-list-json',
            'name' => 'To Duck List Php',
            'description' => 'Descrizione',
            'image' => '/img/projects/to-duck-list.jpg',
            'created_on' => '2023-05-04',
            'fe_be_oriented' => false,
            'technology_id' => 7,
        ],
        [
            'repo_name' => 'laravel-comics',
            'repo_link' => 'https://github.com/Dan848/laravel-comics',
            'name' => 'Dc Comics Laravel',
            'description' => 'Descrizione',
            'image' => '/img/projects/comics.jpg',
            'created_on' => '2023-05-09',
            'fe_be_oriented' => false,
            'technology_id' => 8,
        ],
    ],
    "technologies" => [
        [
            "name" => "HTML & CSS Plain",
            "image" => "/img/technologies/html5.png",
        ],
        [
            "name" => "Javascript Plain",
            "image" => "/img/technologies/javascript.png",
        ],
        [
            "name" => "Bootstrap",
            "image" => "/img/technologies/bootstrap.png",
        ],
        [
            "name" => "Tailwind",
            "image" => "/img/technologies/tailwind.png",
        ],
        [
            "name" => "Vue",
            "image" => "/img/technologies/vue.png",
        ],
        [
            "name" => "Vite",
            "image" => "/img/technologies/vite.png",
        ],
        [
            "name" => "Php Plain",
            "image" => "/img/technologies/php.png",
        ],
        [
            "name" => "Laravel",
            "image" => "/img/technologies/laravel.png",
        ],
    ],
    "dev_languages" => [
        [
            "name" => "HTML",
            "image" => "/img/technologies/html5.png",
        ],
        [
            "name" => "CSS",
            "image" => "/img/technologies/css3.png",
        ],
        [
            "name" => "Sass",
            "image" => "/img/technologies/sass.png",
        ],
        [
            "name" => "Javascript",
            "image" => "/img/technologies/javascript.png",
        ],
        [
            "name" => "PHP",
            "image" => "/img/technologies/php.png",
        ],

    ]
];
