<?php
return [
    "projects" => [
        [
            'repo_name' => 'html-css-toboolist',
            'repo_link' => 'https://github.com/Dan848/html-css-toboolist',
            'name' => 'To BooList Layout',
            'description' => 'Descrizione',
            'image' => '/img/to-boo-list.jpg',
            'created_on' => '2023-01-31',
        ],
        [
            'repo_name' => 'htmlcss-discord',
            'repo_link' => 'https://github.com/Dan848/htmlcss-discord',
            'name' => 'Discord Layout',
            'description' => 'Descrizione',
            'image' => '/img/discord.jpg',
            'created_on' => '2023-02-07',
        ],
        [
            'repo_name' => 'htmlcss-dropbox',
            'repo_link' => 'https://github.com/Dan848/htmlcss-dropbox',
            'name' => 'Dropbox Layout',
            'description' => 'Descrizione',
            'image' => '/img/dropbox.jpg',
            'created_on' => '2023-02-13',
        ],
        [
            'repo_name' => 'html-css-spotifyweb',
            'repo_link' => 'https://github.com/Dan848/html-css-spotifyweb',
            'name' => 'Spotifyweb Layout',
            'description' => 'Descrizione',
            'image' => '/img/spotify.jpg',
            'created_on' => '2023-02-22',
        ],
        [
            'repo_name' => 'html-css-bootstrap-dashboard',
            'repo_link' => 'https://github.com/Dan848/html-css-bootstrap-dashboard',
            'name' => 'Bootstrap Dashboard Layout',
            'description' => 'Descrizione',
            'image' => '/img/bootstrap-dashboard.jpg',
            'created_on' => '2023-03-01',
        ],
        [
            'repo_name' => 'js-campominato-dom',
            'repo_link' => 'https://github.com/Dan848/js-campominato-dom',
            'name' => 'Campo Minato Javascript',
            'description' => 'Descrizione',
            'image' => '/img/campo-minato.jpg',
            'created_on' => '2023-03-21',
        ],
        [
            'repo_name' => 'vue-todolist',
            'repo_link' => 'https://github.com/Dan848/vue-todolist',
            'name' => 'To Duck List Vue',
            'description' => 'Descrizione',
            'image' => '/img/to-duck-list.jpg',
            'created_on' => '2023-03-30',
        ],
        [
            'repo_name' => 'vue-boolzapp',
            'repo_link' => 'https://github.com/Dan848/vue-boolzapp',
            'name' => 'Boolzapp Vue',
            'description' => 'Descrizione',
            'image' => '/img/boolzapp.jpg',
            'created_on' => '2023-04-11',
        ],
        [
            'repo_name' => 'vite-boolflix',
            'repo_link' => 'https://github.com/Dan848/vite-boolflix',
            'name' => 'Boolflix Vite',
            'description' => 'Descrizione',
            'image' => '/img/boolflix.jpg',
            'created_on' => '2023-04-26',
        ],
        [
            'repo_name' => 'proj-html-vuejs',
            'repo_link' => 'https://github.com/Dan848/proj-html-vuejs',
            'name' => 'Anidio Page',
            'description' => 'Descrizione',
            'image' => '/img/anidio.jpg',
            'created_on' => '2023-04-28',
        ],
        [
            'repo_name' => 'php-badwords',
            'repo_link' => 'https://github.com/Dan848/php-badwords',
            'name' => 'Badwords Php',
            'description' => 'Descrizione',
            'image' => '/img/badwords.jpg',
            'created_on' => '2023-04-28',
        ],
        [
            'repo_name' => 'php-todo-list-json',
            'repo_link' => 'https://github.com/Dan848/php-todo-list-json',
            'name' => 'To Duck List Php',
            'description' => 'Descrizione',
            'image' => '/img/to-duck-list.jpg',
            'created_on' => '2023-05-04',
        ],
        [
            'repo_name' => 'laravel-comics',
            'repo_link' => 'https://github.com/Dan848/laravel-comics',
            'name' => 'Dc Comics Laravel',
            'description' => 'Descrizione',
            'image' => '/img/comics.jpg',
            'created_on' => '2023-05-09',
        ],
    ],
];
